[workspace]
resolver = "2"
members = ["pvg", "pixiv"]

[profile.release]
strip = true
lto = true

[profile.release-thinlto]
inherits = "release"
lto = "thin"

[profile.debuginfo]
inherits = "release-thinlto"
debug = true
strip = false
